# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

to_stan <- function(name) {
    .Call('_PStrata_to_stan', PACKAGE = 'PStrata', name)
}

